---
- name: CONFIGURE CISCO SWITCH PORT
  hosts: all
  connection: network_cli
  gather_facts: no

  vars:
    interface_name: GigabitEthernet0/8
    access_vlan: 1



  tasks:
    
    ios_l2_interfaces:
    config:
      - name: "{{ interface_name }}"
        access:
          vlan: "{{ access_vlan }"
    state: overridden