---
- name: GENERATE HSRP REPORT  
  hosts: all
  connection: network_cli
  gather_facts: no

  roles:
    - ansible-network.network-engine

  tasks:

  - name: SHOW INTERFACE
    ios_command:
      commands: show interface
    register: interface_output
  
  - name: PARSE SHOW INTERFACES
    command_parser:
      file: "parsers/show_interfaces.yml"
      content: "{{ interface_output.stdout[0] }}"

  - debug:
      msg: "{{ interface_facts }}"
