---
- name: CISCO SNMP CHECK
  hosts: all
  connection: network_cli
  gather_facts: no

  roles:
    - gather_facts


  vars:
    snmp_host: NOT_FOUND
    snmp_version: NOT_FOUND
    snmp_community: NOT_FOUND

  tasks:

    - name: GET HOSTNAME
      cli_command:
        command: show running-config | include hostname
      register: hostname_output

    - name: FINDING SNMP-SERVER HOSTS
      cli_command:
        command: show running-config | include snmp-server host 1.2.3.4
      register: snmp_hosts_output

    - name:  CREATE REPORT
      vars:
        snmp_host: "{{ item.split()[2] }}"
        snmp_version: "{{ item.split()[4] }}"
        snmp_community: "{{ item.split()[5] }}"
      lineinfile:
        path: ./snmp_check/ansible_snmp_report.csv
        insertafter: 'EOF'
        line: "{{ hostname }},{{ inventory_hostname }},{{ snmp_host }},{{ snmp_community }}"
      with_items: "{{ snmp_hosts_output.stdout_lines[0] }}"
      when: "'1.2.3.4' in snmp_hosts_output.stdout[0]"
      tags: 
        - snmp_report
   
...


       
     