---

- name: REMOVE EXISTING USERS
  ios_user:
    purge: yes
  when: cisco_purge_users is True

- name: ADD NEW USERNAME
  ios_user: 
     name: {{ cisco_new_user }}          
     configured_password: {{ cisco_user_password }}
     password_type: password
     privilege: {{ cisco_user_priv }}

     